apiVersion: v1
kind: Service
metadata:
  labels:
    app: golang-helloworld
  name: golang-helloworld
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: golang-helloworld