apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golang-helloworld
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: ocp
    repoURL: 'https://github.com/dbgjerez/ocp-monitoring-golang.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
