apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kustomize-bootstrap
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - env: dev
  template:
    metadata:
      name: 'kustomize-{{env}}-helloworld'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: 'https://github.com/dbgjerez/ocp-monitoring-golang.git'
        targetRevision: HEAD
        path: 'ocp/overlays/{{env}}'
      destination:
        namespace: '{{env}}-monitoring'
        server: 'https://kubernetes.default.svc'